# Generated by Django 4.2.7 on 2024-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
