# Generated by Django 4.2.7 on 2024-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_like_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
