# Generated by Django 4.2.7 on 2024-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_like_object_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='posts_like_content_4ca6af_idx',
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
