# Generated by Django 4.2.7 on 2024-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_like_posts_like_content_4ca6af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
