# Generated by Django 4.2.7 on 2024-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like_liked_alter_like_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
